# Builds FRONTEND and BACKEND and pushes :latest and :$SHORT_SHA tags.
# Logs go to your bucket so the custom SA trigger runs.

substitutions:
  _REGION: europe-north1
  _AR_HOST: '${_REGION}-docker.pkg.dev/${PROJECT_ID}'
  _FRONT_REPO: nkv2-frontend
  _BACK_REPO: nkv2-backend
  _LOGS_BUCKET: 'gs://nikysite-build-logs'

steps:
  # ---------- FRONTEND ----------
  - name: 'gcr.io/cloud-builders/docker'
    # Build context is the frontend folder.
    # Dockerfile stays at infra/development/Docker/frontend.Dockerfile.
    args:
      [
        'build',
        '-f',
        'infra/development/Docker/frontend.Dockerfile',
        '-t',
        '${_AR_HOST}/${_FRONT_REPO}:latest',
        '-t',
        '${_AR_HOST}/${_FRONT_REPO}:${SHORT_SHA}',
        'frontend',
      ]

  # ---------- BACKEND ----------
  - name: 'gcr.io/cloud-builders/docker'
    # Build context is the backend folder.
    args:
      [
        'build',
        '-f',
        'infra/development/Docker/backend.Dockerfile',
        '-t',
        '${_AR_HOST}/${_BACK_REPO}:latest',
        '-t',
        '${_AR_HOST}/${_BACK_REPO}:${SHORT_SHA}',
        'backend',
      ]

# Cloud Build will push any tags listed here after the steps complete.
images:
  - '${_AR_HOST}/${_FRONT_REPO}:latest'
  - '${_AR_HOST}/${_FRONT_REPO}:${SHORT_SHA}'
  - '${_AR_HOST}/${_BACK_REPO}:latest'
  - '${_AR_HOST}/${_BACK_REPO}:${SHORT_SHA}'

# Required for custom SA builds.
options:
  logging: GCS_ONLY

logsBucket: '${_LOGS_BUCKET}'
