logsBucket: gs://nikysite-build-logs
options:
  logging: GCS_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - infra/development/Docker/backend.Dockerfile
      - -t
      - europe-north1-docker.pkg.dev/$PROJECT_ID/nkv2-backend/backend:$SHORT_SHA
      - .

images:
  - europe-north1-docker.pkg.dev/$PROJECT_ID/nkv2-backend/backend:$SHORT_SHA
