substitutions:
  _REGION: europe-north1
  _FRONTEND_REPO: nkv2-frontend
  _BACKEND_REPO: nkv2-backend
  # Full image repository paths (repository + image name)
  _FRONTEND_IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_FRONTEND_REPO}/nkv2-frontend
  _BACKEND_IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_BACKEND_REPO}/nkv2-backend

# RESOURCES - adjust to production images instead
steps:
  # ---------- FRONTEND ----------
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - infra/production/Docker/frontend.Dockerfile
      - -t
      - ${_FRONTEND_IMAGE}:${SHORT_SHA}
      - -t
      - ${_FRONTEND_IMAGE}:latest
      - ./frontend

  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_FRONTEND_IMAGE}:${SHORT_SHA}']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_FRONTEND_IMAGE}:latest']

  # ---------- BACKEND ----------
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - infra/production/Docker/backend.Dockerfile
      - -t
      - ${_BACKEND_IMAGE}:${SHORT_SHA}
      - -t
      - ${_BACKEND_IMAGE}:latest
      - ./backend

  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_BACKEND_IMAGE}:${SHORT_SHA}']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_BACKEND_IMAGE}:latest']

# Use your user-managed logs bucket
logsBucket: gs://nikysite-build-logs
options:
  logging: GCS_ONLY
